export const backends = [
  {
    id: "1",
    title: "Express Js",
    deskripsi: "Belajar Express dasar",
    paragraf1: "",
    paragraf2: "",
    paragraf3: "",
    contoh: "",
    penjelasan: "",
    logo: "",
    color: "",
    border: "",
  },
  {
    id: "2",
    title: "Sequelize - CLI",
    deskripsi: "Belajar Sequelize - CLI dasar",
    paragraf1: "",
    paragraf2: "",
    paragraf3: "",
    contoh: "",
    penjelasan: "",
    logo: "",
    color: "",
    border: "",
  },
  {
    id: "1",
    title: "Mysql",
    deskripsi: "Belajar Mysql dasar",
    paragraf1: "",
    paragraf2: "",
    paragraf3: "",
    contoh: "",
    penjelasan: "",
    logo: "",
    color: "",
    border: "",
  },
];
